image: alpine:latest
variables:
  DOCKER_TLS_CERTDIR: ""


stages:
#  - test
  - unit-test
  - package-deps
  - package-build
  - package-test
  - release
  - publish

include:
#  - template: Code-Quality.gitlab-ci.yml
  - local: '/.gitlab-ci/Jobs/php_unit_tests.yml'
#  - local: '/.gitlab-ci/Jobs/artifact_build.yml'
#  - local: '/.gitlab-ci/Jobs/debian_package_build.yml'
  - local: '/.gitlab-ci/Jobs/style_check.yml'

cache:
  paths:
    - vendor/


